name: DriftFX Build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare
      run: sudo apt-get install -y mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev
    - uses: actions/checkout@v1
    - name: Configure Build
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles" ../native
    - name: Build
      run: |
        cd build
        cmake --build .
    - name: Prepare artifacts
      run: |
        mkdir artifacts
        cp DriftFX/libdriftfx.so artifacts
        cp DriftFX/libdriftfx.so.debug atrifacts
        cp samples/libsamples.so artifacts
        cp samples/libsamples.so.debug artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: native-linux
        path: artifacts

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure Build
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles" ../native
    - name: Build
      run: |
        cd build
        cmake --build .
    - name: Prepare artifacts
      run: |
        mkdir artifacts
        cp DriftFX/libdriftfx.dylib artifacts
        cp -r DriftFX/libdriftfx.dylib.dSYM artifacts
        cp samples/libsamples.dylib artifacts
        cp -r samples/libsamples.dylib.dSYM artifacts
    - name: Upload atrifacts
      uses: actions/upload-artifact@v1
      with:
        name: native-macos
        path: artifacts

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure Build (cmake)
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" ../native
    - name: Build
      run: |
        cd build
        cmake --build . --config RelWithDebInfo
    - name: Prepare artifacts
      run: |
        mkdir artifacts
        cp DriftFX/RelWithDebInfo/driftfx.dll artifacts
        cp DriftFX/RelWithDebInfo/driftfx.lib artifacts
        cp DriftFX/RelWithDebInfo/driftfx.pdb artifacts
        cp samples/RelWithDebInfo/samples.dll artifacts
        cp samples/RelWithDebInfo/samples.lib artifacts
        cp samples/RelWithDebInfo/samples.pdb artifacts
    - name: Upload atrifacts
      uses: actions/upload-artifact@v1
      with:
        name: native-macos
        path: artifacts

  build-maven:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk+fx
    - name: Build with Maven
      run: mvn -B package --file pom.xml

