name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk+fx
    - name: Download Java 11
      run: wget -q https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.5%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.5_10.tar.gz
    - name: Extract JDK 11
      uses: brunoborges/justextract@master
      with:
        file: OpenJDK11U-jdk_x64_linux_hotspot_11.0.5_10.tar.gz
#    - name: Inspect file system
#      run: pwd; ls -la; ls -la jdk-11.0.5+10
#    - name: Setup toolchain
#      run: mkdir .m2; cp tools/toolchains-github-actions.xml .m2/toolchains.xml
    - name: Run Maven build
      run: mvn -B package --file pom.xml --global-toolchains tools/toolchains-github-actions.xml
#    - name: Build with Maven
#      run: mvn -B package --file pom.xml
