name: Native Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Prepare
      run: sudo apt-get install mesa-common-dev
    - uses: actions/checkout@v1
    - name: cmake
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=DEBUG -G "Unix Makefiles" ../native
    - name: make
      run: |
        make
