name: Native Windows

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
#    - name: Prepare
#      run: |
#        choco install something
    - name: List cmake generators
      run: cmake --help
    - uses: actions/checkout@v1
    - name: Configure Build (cmake)
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" ../native
    - name: Build
      run: |
        cd build
        cmake --build . --config RelWithDebInfo
        
