name: Native Linux

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
#    - name: Prepare
#      run: sudo apt-get install -y mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev
    - uses: actions/checkout@v1
    - name: Configure Build
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles" ../native
    - name: Build
      run: |
        cd build
        cmake --build .
